Laravel-Vercel Deploy and Swagger UI
iaw-2023/AI-Avengers-Laravel pull request #3
Opened 2023-06-16 18:35 UTC by zucolieze

Link deploy en Vercel: [https://ai-avengers-laravel-8cvqnlupu-zucolieze.vercel.app/](url)

Link de Swagger UI: [https://ai-avengers-laravel-8cvqnlupu-zucolieze.vercel.app/rest/documentation](url)

2023-06-20 15:41 UTC, hfmartinez85 requested changes
Se requiere corregir los siguientes puntos:

* Sacar la pantalla por defecto de Laravel. Podría dirigirse directamente a la pantalla de login.
* La aplicación no debería permitir el registro de nuevos usuarios. Desactivar, y verificar que no se pueda ingresar por URL.
* El dashboard vacío no sería necesario. Se podría redirigir directamente a Home una vez logueado.
* Marcas: no se debería tener que ingresar el ID manualmente, debería ser asignado automáticamente por la base de datos. Si no se completa alguno de los campos, se exhibe un error de base de datos. La aplicación debería ser robusta, utilizando los controles que da el framework, para que no se permita hacer un submit sin completar campos obligatorios.

![image](https://github.com/iaw-2023/AI-Avengers-Laravel/assets/50154762/d98cc1e3-93c0-45aa-89da-796a91886d74)

* Se permite borrar marcas que están siendo referenciadas por vehículos. No debería ocurrir.
* Vehículos: misma observación del ID y error de BD al guardar. 
* Para la selección de las marcas, debería ofrecerse un combo con opciones, no un campo de texto para ingresar un ID. En el listado, en lugar de mostrar el ID de marcas, se debería mostrar el nombre.
* Se permite borrar vehículos que están referenciados en reservas. No debería ocurrir.
* Los endpoints de la API debería devolver JSON, no HTML.

![image](https://github.com/iaw-2023/AI-Avengers-Laravel/assets/50154762/1324fd39-b2f6-4660-be27-fd1c8de7b6c1)

* Por otra parte, no vi las migrations en el código. Deberían estar.

2023-06-25 14:46 UTC, zucolieze commented
Luego de las correciones cambiaron los link de deploy y de la documentacion de la API.

Link deploy en Vercel: [https://ai-avengers-laravel-1gmnzof48-zucolieze.vercel.app/](url)

Link de Swagger UI: [https://ai-avengers-laravel-1gmnzof48-zucolieze.vercel.app/rest/documentation](url)

(Las migraciones fueron mergeadas en la primer entrega y estan dentro del main)

2023-06-26 18:04 UTC, hfmartinez85 requested changes
No se corrigió lo siguiente:

* Vehículos: En el listado, en lugar de mostrar el ID de marcas, se debería mostrar el nombre.

![image](https://github.com/iaw-2023/AI-Avengers-Laravel/assets/50154762/546869f2-7aa4-4044-9c32-9d4863c7ab59)

* Por otra parte, es necesario proveer en la API un endpoint para poder crear una nueva reserva, ya que es requerido para el proyecto JS. Revisé acá: https://ai-avengers-laravel-git-laravel-zucolieze.vercel.app/rest/documentation

2023-06-27 13:13 UTC, zucolieze commented
Luego de las correciones cambiaron los link de deploy y de la documentacion de la API. Ahora en la documentacion de Swagger esta el metodo "crearReserva" para el endpoint, que solicita un email y dos fechas para el inicio y final de la reserva.

Link deploy en Vercel: [https://ai-avengers-laravel-fzbisgnlb-zucolieze.vercel.app/](url)

Link de Swagger UI: [https://ai-avengers-laravel-fzbisgnlb-zucolieze.vercel.app/rest/documentation](url)

2023-06-27 13:43 UTC, hfmartinez85 commented
> 

Hola,

La parte de las marcas está OK. Con respecto a la reserva: ¿cómo se indica qué vehículos se están reservando?

Saludos

2023-07-02 03:19 UTC, hfmartinez85 approved these changes

2023-09-18 20:10 UTC, merged